import Head from "next/head";
import Image from "next/image";

//mui
import { Box, Typography, Grid, Paper } from "@mui/material";
import { grey } from "@mui/material/colors";

//svg icons
import facebook from "../public/svg/icon-facebook.svg";
import twitter from "../public/svg/icon-twitter.svg";
import pinterest from "../public/svg/icon-pinterest.svg";
import instagram from "../public/svg/icon-instagram.svg";

export default function Home() {
  let images = [
    "/images/image-deep-earth.jpg",
    "/images/image-night-arcade.jpg",
    "/images/image-soccer-team.jpg",
    "/images/image-grid.jpg",
    "/images/image-from-above.jpg",
    "/images/image-pocket-borealis.jpg",
    "/images/image-curiosity.jpg",
    "/images/image-fisheye.jpg",
  ];

  return (
    <>
      <Head>
        <title>Loop Studios</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box component="div" className="home-container">
        <Box
          component="header"
          sx={{
            py: { phone: 5, laptop: 8},
            px: {phone: 5, laptop: 12},
            backgroundImage: "url(/images/image-hero.jpg)",
            height: { tabletxl: "40vh", laptop: "50vh", desktop: "70vh" },
          }}
        >
          <Box
            component="nav"
            sx={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
            }}
          >
            <Typography

              variant="subtitle1"
              component="a"
              sx={{ color: "white", fontSize: {laptop: "1.3rem"}, fontWeight: 700 }}
            >
              loopstudios
            </Typography>

            <Paper
              elevation={0}
              className="nav-links"
              sx={{
                display: { phone: "none", tabletxl: "flex" },
                background: "none",
              }}
            >
              <Typography
                component="a"
                sx={{
                  fontSize: { tabletxl: ".75rem", laptop: ".9rem" },
                  textDecoration: "none",
                  mr: 2,
                  pb: 1,
                  color: "grey.400",
                  fontWeight: 600,
                  borderBottom: "3px solid rgba(255, 255, 255, 0)",
                  transition: "all .5s",
                  "&:hover": {
                    color: "white",
                    borderBottom: "3px solid rgba(255, 255, 255)",
                  },
                }}
              >
                About
              </Typography>

              <Typography
                component="a"
                sx={{
                  fontSize: { tabletxl: ".75rem", laptop: ".9rem" },
                  textDecoration: "none",
                  mr: 2,
                  pb: 1,
                  color: "grey.400",
                  fontWeight: 600,
                  borderBottom: "3px solid rgba(255, 255, 255, 0)",
                  transition: "all .5s",
                  "&:hover": {
                    color: "white",
                    borderBottom: "2px solid rgba(255, 255, 255)",
                  },
                }}
              >
                Careers
              </Typography>

              <Typography
                component="a"
                sx={{
                  fontSize: { tabletxl: ".75rem", laptop: ".9rem" },
                  textDecoration: "none",
                  mr: 2,
                  pb: 1,
                  color: "grey.400",
                  fontWeight: 600,
                  borderBottom: "3px solid rgba(255, 255, 255, 0)",
                  transition: "all .5s",
                  "&:hover": {
                    color: "white",
                    borderBottom: "2px solid rgba(255, 255, 255)",
                  },
                }}
              >
                Events
              </Typography>

              <Typography
                component="a"
                sx={{
                  fontSize: { tabletxl: ".75rem", laptop: ".9rem" },
                  textDecoration: "none",
                  mr: 2,
                  pb: 1,
                  color: "grey.400",
                  fontWeight: 600,
                  borderBottom: "3px solid rgba(255, 255, 255, 0)",
                  transition: "all .5s",
                  "&:hover": {
                    color: "white",
                    borderBottom: "2px solid rgba(255, 255, 255)",
                  },
                }}
              >
                Products
              </Typography>

              <Typography
                component="a"
                sx={{
                  fontSize: { tabletxl: ".75rem", laptop: ".9rem" },
                  textDecoration: "none",
                  mr: 2,
                  pb: 1,
                  color: "grey.400",
                  fontWeight: 600,
                  borderBottom: "3px solid rgba(255, 255, 255, 0)",
                  transition: "all .5s",
                  "&:hover": {
                    color: "white",
                    borderBottom: "2px solid rgba(255, 255, 255)",
                  },
                }}
              >
                Support
              </Typography>
            </Paper>

            <Box
              component="div"
              className="hamburger"
              sx={{
                m: 1,
                display: { phone: "flex", tabletxl: "none" },
                flexDirection: "column",
                justifyContent: "space-between",
                height: "1rem",
                width: "1.5rem",
              }}
            >
              <Box
                component="div"
                sx={{ width: "100%", height: "10%", backgroundColor: "white" }}
              >
                {" "}
              </Box>
              <Box
                component="div"
                sx={{ width: "100%", height: "10%", backgroundColor: "white" }}
              >
                {" "}
              </Box>
              <Box
                component="div"
                sx={{ width: "100%", height: "10%", backgroundColor: "white" }}
              >
                {" "}
              </Box>
            </Box>
          </Box>

          <Box
            component="section"
            className="header-container"
            sx={{ my: { phone: 5, tabletxl: 10 } }}
          >
            <Grid container>
              <Paper
                elevation={0}
                sx={{
                  p: 3,
                  px: {laptop: 6},
                  borderRadius: "0px",
                  border: "3px solid white",
                  background: "none",
                  width: { tablet: "65%" },
                  maxWidth: { tabletxl: "420px" },
                }}
              >
                <Typography variant="h1" sx={{ color: "white" }}>
                  IMMERSIVE EXPERIENCES THAT DELIVER
                </Typography>
              </Paper>
            </Grid>
          </Box>
        </Box>

        <Box component="main" sx={{ m: {phone: 5, laptop: 20} }}>
          <Grid
            container
            component="section"
            sx={{ my: 10, position: "relative" }}
          >
            <Grid
              item
              phone={12}
              tabletxl={7}
              sx={{ height: { phone: "25vh", tabletxl: "40vh", laptop: '50vh', desktop: '60vh' } }}
            >
              <Box
                sx={{
                  m: 0,
                  p: 0,
                  width: "100%",
                  height: "100%",
                  position: "relative",
                }}
              >
                <Image
                  src="/images/image-interactive.jpg"
                  layout="fill"
                  alt=""
                  className="interactive-image"
                />
              </Box>
            </Grid>

            <Grid
              item
              phone={0}
              tabletxl={5}
              sx={{ height: { tabletxl: "50vh", laptop: "65vh" } }}
            ></Grid>

            <Grid
              item
              phone={12}
              tabletxl={7}
              sx={{
                position: { phone: "relative", tabletxl: "absolute" },
                bottom: 0,
                right: {phone: 0, laptop: 150},
              }}
            >
              <Paper
                elevation={0}
                sx={{
                  p: 5,
                  px: { phone: 7, tabletxl: 6 },
                  width: { tabletxl: "100%" },
                  maxWidth: { tabletxl: "420px" },
                }}
              >
                <Typography
                  variant="h2"
                  sx={{ mb: 3, width: { phone: "80%" } }}
                >
                  THE LEADER IN INTERACTIVE VR
                </Typography>

                <Typography variant="body1" sx={{ color: "grey.400" }}>
                  Founded in 2011, Loopstudios has been producing world-class
                  virtual reality projects for some of the best companies around
                  the globe. Our award-winning creations have transformed
                  buisnesses through digital experiences that bind to their
                  brand.
                </Typography>
              </Paper>
            </Grid>
          </Grid>

          <Grid container component="section" sx={{ my: 10 }}>
            <Paper
              elevation={0}
              sx={{
                m: 0,
                mb: 2,
                p: 0,
                display: "flex",
                justifyContent: "space-between",
                alignItems: "baseline",
                width: "100%",
              }}
            >
              <Typography variant="h3">Our Creation</Typography>

              <Box
                component="button"
                sx={{
                  m: 0,
                  px: 1.2,
                  py: 0.8,
                  border: "2px solid black",
                  backgroundColor: "white",
                  letterSpacing: "5px",
                  fontSize: {
                    phone: ".5rem",
                    tabletxl: ".65rem",
                    laptop: ".75rem",
                  },
                  cursor: "pointer",
                }}
              >
                SEE ALL
              </Box>
            </Paper>

            <Grid container className="gallery">
              {images.map((img) => (
                <Grid
                  key={Math.floor(Math.random() * 1000)}
                  item
                  phone={12}
                  tablet={5.5}
                  tabletxl={3.5}
                  laptop={2.7}
                  sx={{
                    my: { phone: 1 },
                    mx: { tablet: "auto" },
                    height: { phone: "25vh", tablet: "30vh", laptop: "50vh" },
                  }}
                >
                  <Paper
                    elevation={0}
                    sx={{
                      m: 0,
                      p: 0,
                      width: "100%",
                      height: "100%",
                      position: "relative",
                    }}
                  >
                    <Image
                      src={img}
                      layout="fill"
                      alt=""
                      className="gallery-image"
                    />
                  </Paper>
                </Grid>
              ))}
            </Grid>
          </Grid>
        </Box>

        <Box
          component="footer"
          sx={{ m: 0, py: {phone: 5}, px: {phone: 5, laptop: 10}, color: "white", backgroundColor: "black" }}
        >
          <Grid
            item
            phone={12}
            sx={{
              display: { tablet: "flex" },
              justifyContent: { tablet: "space-between" },
            }}
          >
            <Paper
              elevation={0}
              className="logo"
              sx={{ background: "none", mb: { phone: 2 } }}
            >
              <Typography
                variant="subtitle2"
                component="a"
                sx={{ color: "white", fontWeight: "600" }}
              >
                loopstudios
              </Typography>
            </Paper>

            <Paper
              elevation={0}
              className="socialmedia-links"
              sx={{ background: "none" }}
            >
              <Box
                component="a"
                sx={{
                  mr: 2,
                  display: "inline-block",
                  width: "1rem",
                  height: "1rem",
                }}
              >
                <Image src={facebook} alt="" />
              </Box>

              <Box
                component="a"
                sx={{
                  mr: 2,
                  display: "inline-block",
                  width: "1rem",
                  height: "1rem",
                }}
              >
                <Image src={twitter} alt="" />
              </Box>

              <Box
                component="a"
                sx={{
                  mr: 2,
                  display: "inline-block",
                  width: "1rem",
                  height: "1rem",
                }}
              >
                <Image src={pinterest} alt="" />
              </Box>

              <Box
                component="a"
                sx={{
                  mr: 2,
                  display: "inline-block",
                  width: "1rem",
                  height: "1rem",
                }}
              >
                <Image src={instagram} alt="" />
              </Box>
            </Paper>
          </Grid>

          <Grid
            item
            phone={12}
            sx={{
              display: { tablet: "flex" },
              justifyContent: { tablet: "space-between" },
            }}
          >
            <Paper
              elevation={0}
              className="footer-links"
              sx={{
                py: 2,
                m: 0,
                width: { phone: "100%", tablet: "50%", laptop: "30%", desktop: "20%" },
                display: "flex",
                justifyContent: "space-between",
                background: "none",
              }}
            >
              <Typography
                component="a"
                sx={{ mr: 2, color: "grey.400", cursor: "pointer" }}
              >
                About
              </Typography>
              <Typography
                component="a"
                sx={{ mr: 2, color: "grey.400", cursor: "pointer" }}
              >
                Careers
              </Typography>
              <Typography
                component="a"
                sx={{ mr: 2, color: "grey.400", cursor: "pointer" }}
              >
                Events
              </Typography>
              <Typography
                component="a"
                sx={{ mr: 2, color: "grey.400", cursor: "pointer" }}
              >
                Products
              </Typography>
              <Typography
                component="a"
                sx={{ color: "grey.400", cursor: "pointer" }}
              >
                Support
              </Typography>
            </Paper>

            <Paper
              item
              elevation={0}
              phone={12}
              sx={{
                py: 2,
                m: 0,
                width: { phone: "100%", tablet: "40%", laptop: "30%" },
                background: "none",
              }}
            >
              <Typography component="p" sx={{ color: "grey.500", textAlign: 'right' }}>
                2022 Loopstudios. All rights reserved.
              </Typography>
            </Paper>
          </Grid>
        </Box>
      </Box>
    </>
  );
}
