// __NEXT JS COMPONENTS__
import Head from "next/head";
import Image from "next/image";

// __MUI COMPONENTS__
import {
	Box,
	Typography,
	Grid,
	Paper,
} from "@mui/material";
import { grey } from "@mui/material/colors";

// __CUSTOM COMPONENTS__
import HomeImageProfile from "../components/HomeImageProfile";

// __SVG ICONS
import facebook from "../public/svg/icon-facebook.svg";
import twitter from "../public/svg/icon-twitter.svg";
import pinterest from "../public/svg/icon-pinterest.svg";
import instagram from "../public/svg/icon-instagram.svg";

export default function Home() {
	return (
		<>
			<Head>
				<title>Loop Studios</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Box className="HOME_PAGE_CONTAINER" sx={{mx: "auto", maxWidth: "1530px"}}>
				<Box
					component="header"
					sx={{
						py: { phone: 5, laptop: 8 },
						pb: { tabletxl: 0 },
						mb: { phone: 15, laptop: 20 },
						height: {
							phone: "30rem",
							tabletxl: "30rem",
							laptop: "37rem",
							desktop: "39rem",
							desktopxl: "40rem",
						},
						maxHeight: { tabletxl: "none" },
						position: "relative",
						"&::before": {
							content: "''",
							position: "absolute",
							top: 0,
							left: 0,
							width: "100%",
							height: "100%",
							backgroundImage: {
								phone: "url(/images/mobile/image-hero.jpg)",
								tabletxl: "url(/images/desktop/image-hero.jpg)",
							},
							backgroundSize: "cover",
							zIndex: -1,
						},
					}}
				>
					<Box
						className="CONTAINER"
						sx={{
							px: { phone: 5 },
							mx: { phone: "auto" },
							display: "flex",
							flexDirection: "column",
							maxWidth: {
								phone: "380px",
								tablet: "420px",
								tabletsm: "530px",
								tabletxl: "700px",
								tabletxll: "740px",
								laptop: "850px",
								desktop: "1000px",
								desktopxl: "1200px",
							},
							height: "100%",
						}}
					>
						<Box
							component="nav"
							sx={{
								width: { phone: "100%" },								
								display: "flex",
								alignItems: "center",
								position: "relative",
								zIndex: 10,
							}}
						>
							<Typography
								variant="subtitle1"
								className="LOGO"
								sx={{
									flex: 1,
								}}
							>
								loopstudios
							</Typography>

							<Box
								className="NAV_LINKS"
								sx={{
									display: {
										phone: "none",
										tabletxll: "flex",
									},
									alignItems: {
										tabletxl:
											"baseline",
									},
								}}
							>
								<Box className="links">
									<Typography
										variant="subtitle2"
										sx={{
											mx: {
												tabletxl: 2,
												laptop: 2,
											},
											color: "grey.200",
										}}
									>
										About
									</Typography>

									<Typography
										variant="subtitle2"
										sx={{
											mx: {
												tabletxl: 2,
												laptop: 2,
											},
										}}
									>
										Careers
									</Typography>

									<Typography
										variant="subtitle2"
										sx={{
											mx: {
												tabletxl: 2,
												laptop: 2,
											},
										}}
									>
										Events
									</Typography>

									<Typography
										variant="subtitle2"
										sx={{
											mx: {
												tabletxl: 2,
												laptop: 2,
											},
										}}
									>
										Products
									</Typography>

									<Typography
										variant="subtitle2"
										sx={{
											mx: {
												tabletxl: 2,
												laptop: 2,
											},
										}}
									>
										Support
									</Typography>
								</Box>
							</Box>

							<Box
								sx={{
									display: {
										phone: "flex",
										tabletxll: "none",
									},
									flexDirection: "column",
									justifyContent:
										"space-between",
									width: "25px",
									height: "15px",
								}}
							>
								<Box
									component="span"
									className="line"
									sx={{
										width: "100%",
										height: {
											phone: "1px",
										},
										backgroundColor:
											"white",
									}}
								></Box>
								<Box
									component="span"
									className="line"
									sx={{
										width: "100%",
										height: {
											phone: ".8px",
										},
										backgroundColor:
											"white",
									}}
								></Box>
								<Box
									component="span"
									className="line"
									sx={{
										width: "100%",
										height: {
											phone: "1px",
										},
										backgroundColor:
											"white",
									}}
								></Box>
							</Box>
						</Box>

						<Box
							component="section"
							className="HEADER_BODY"
							sx={{
								my: { phone: "auto", laptop: 0 },
								mt: {laptop: "17%", desktop: "15%"},
								mx: {
									phone: "auto",
									tabletsm: 0,
								},
								width: { phone: "100%" },
								maxWidth: {
									tabletxl: "480px",
									desktop: "500px",
								},
								//height: {tabletsm: "10rem"}
							}}
						>
							<Paper
								elevation={0}
								sx={{
									p: {
										phone: 3,
										tablet: 5,
										tabletsm: 5,
									},
									px: { laptop: 6 },
									borderRadius: "0px",
									border: "3px solid white",
									background: "none",
									height: {
										tabletsm: "100%",
									},
									display: "flex",
									alignItems: "center",
								}}
							>
								<Typography
									variant="h1"
									sx={{
										color: "white",
										width: {
											tabletxl:
												"291px",
											desktop:
												"300px",
										},
									}}
								>
									IMMERSIVE EXPERIENCES
									THAT DELIVER
								</Typography>
							</Paper>
						</Box>
					</Box>
				</Box>

				<Box
					component="main"
					sx={{
						mb: { phone: 15, laptop: 20 },
						mx: { phone: "auto" },
						px: { phone: 5 },
						width: { phone: "100%" },						
						maxWidth: {
							phone: "380px",
							tablet: "420px",
							tabletsm: "530px",
							tabletxl: "700px",
							tabletxll: "740px",
							laptop: "850px",
							desktop: "1000px",
							desktopxl: "1200px",
						},
					}}
				>
					<Box
						component="section"
						sx={{
							mb: { phone: 15 },
							position: "relative",
							height: {
								tabletsm: "27rem",
								laptop: "35rem",
								desktop: "35rem",
							},
							// backgroundColor: "grey.200",
						}}
					>
						<Box
							sx={{
								mb: {
									phone: 5,
									tabletsm: 0,
								},
								height: {
									phone: "50vw",
									tablet: "55vw",
									tabletsm: "60vw",
									tabletxl: "49vw",
									laptop: "50vw",
									desktop: "40vw",
								},
								maxHeight: {desktop: "450px"},
								width: {
									phone: "100%",
									tabletsm: "80%",
									tabletxl: "75%",
									desktop: "75%",
								},
								position: "relative",
							}}
							className="IMAGE_CONTAINER"
						>
							<Image
								src="/images/desktop/image-interactive.jpg"
								alt="Picture of am man wearing a vr head set"
								layout="fill"
								objectFit="contain"
								className="interactive-image"
							/>
						</Box>

						<Box
							phone={12}
							tabletsm={8}
							sx={{
								mx: { phone: "auto" },
								px: { tabletsm: 5, desktop: 7 },
								maxWidth: {
									phone: "280px",
									tabletxl: "300px",
									laptop: "400px",
									desktop: "460px",
								},
								height: {
									phone: "200px",
									tabletsm: "240px",
									tabletxl: "240px",
									laptop: "280px",
									desktop: "300px",
								},
								position: {
									phone: "relative",
									tabletsm: "absolute",
								},
								bottom: 0,
								right: {
									tabletsm: 0,
									laptop: 0,
								},
								backgroundColor: "white",
							}}
						>
							<Paper
								elevation={0}
								sx={{
									borderRadius: "0px",
									width: "100%",
									height: "100%",
									display: "flex",
									flexDirection: "column",
									justifyContent:
										"center",
								}}
							>
								<Typography
									variant="h2"
									sx={{
										mb: 3,
										width: {
											phone: "80%",
										},
										color: "black",
									}}
								>
									THE LEADER IN
									INTERACTIVE VR
								</Typography>

								<Typography
									variant="body1"
									sx={{
										color: "grey.400",
									}}
								>
									Founded in 2011,
									Loopstudios has been
									producing world-class
									virtual reality projects
									for some of the best
									companies around the
									globe. Our award-winning
									creations have
									transformed buisnesses
									through digital
									experiences that bind to
									their brand.
								</Typography>
							</Paper>
						</Box>
					</Box>

					<Box						
						component="section"						
					>
						<Paper
							elevation={0}
							sx={{
								m: 0,
								mb: 2,
								p: 0,
								display: "flex",
								justifyContent:
									"space-between",
								alignItems: "baseline",
								width: "100%",
							}}
						>
							<Typography
								variant="h3"
								sx={{ color: "black" }}
							>
								Our Creation
							</Typography>

							<Box
								component="button"
								sx={{
									m: 0,
									px: 1.2,
									py: 0.8,
									border: "2px solid black",
									backgroundColor:
										"white",
									color: "black",
									letterSpacing: "5px",
									fontSize: {
										phone: ".5rem",
										tabletxl: ".65rem",
										laptop: ".75rem",
									},
									cursor: "pointer",
								}}
							>
								SEE ALL
							</Box>
						</Paper>

						<Grid
							container
							className="gallery"
							sx={{ position: "relative" }}
						>
							<HomeImageProfile option={0} />
							<HomeImageProfile option={1} />
							<HomeImageProfile option={2} />
							<HomeImageProfile option={3} />
							<HomeImageProfile option={4} />
							<HomeImageProfile option={5} />
							<HomeImageProfile option={6} />
							<HomeImageProfile option={7} />
						</Grid>
					</Box>
				</Box>

				<Box
					component="footer"
					sx={{
						m: 0,
						py: { phone: 5 },
						px: { phone: 5, laptop: 10 },
						color: "white",
						backgroundColor: "black",
					}}
				>
					<Grid
						item
						phone={12}
						sx={{
							display: { tablet: "flex" },
							justifyContent: {
								tablet: "space-between",
							},
						}}
					>
						<Paper
							elevation={0}
							className="logo"
							sx={{
								background: "none",
								mb: { phone: 2 },
							}}
						>
							<Typography
								variant="subtitle2"
								component="a"
								sx={{
									color: "white",
									fontWeight: "600",
								}}
							>
								loopstudios
							</Typography>
						</Paper>

						<Paper
							elevation={0}
							className="socialmedia-links"
							sx={{ background: "none" }}
						>
							<Box
								component="a"
								sx={{
									mr: 2,
									display: "inline-block",
									width: "1rem",
									height: "1rem",
								}}
							>
								<Image
									src={facebook}
									alt=""
								/>
							</Box>

							<Box
								component="a"
								sx={{
									mr: 2,
									display: "inline-block",
									width: "1rem",
									height: "1rem",
								}}
							>
								<Image
									src={twitter}
									alt=""
								/>
							</Box>

							<Box
								component="a"
								sx={{
									mr: 2,
									display: "inline-block",
									width: "1rem",
									height: "1rem",
								}}
							>
								<Image
									src={pinterest}
									alt=""
								/>
							</Box>

							<Box
								component="a"
								sx={{
									mr: 2,
									display: "inline-block",
									width: "1rem",
									height: "1rem",
								}}
							>
								<Image
									src={instagram}
									alt=""
								/>
							</Box>
						</Paper>
					</Grid>

					<Grid
						item
						phone={12}
						sx={{
							display: { tablet: "flex" },
							justifyContent: {
								tablet: "space-between",
							},
						}}
					>
						<Paper
							elevation={0}
							className="footer-links"
							sx={{
								py: 2,
								m: 0,
								width: {
									phone: "100%",
									tablet: "50%",
									laptop: "30%",
									desktop: "20%",
								},
								display: "flex",
								justifyContent:
									"space-between",
								background: "none",
							}}
						>
							<Typography
								component="a"
								sx={{
									mr: 2,
									color: "grey.400",
									cursor: "pointer",
								}}
							>
								About
							</Typography>
							<Typography
								component="a"
								sx={{
									mr: 2,
									color: "grey.400",
									cursor: "pointer",
								}}
							>
								Careers
							</Typography>
							<Typography
								component="a"
								sx={{
									mr: 2,
									color: "grey.400",
									cursor: "pointer",
								}}
							>
								Events
							</Typography>
							<Typography
								component="a"
								sx={{
									mr: 2,
									color: "grey.400",
									cursor: "pointer",
								}}
							>
								Products
							</Typography>
							<Typography
								component="a"
								sx={{
									color: "grey.400",
									cursor: "pointer",
								}}
							>
								Support
							</Typography>
						</Paper>

						<Paper
							elevation={0}
							phone={12}
							sx={{
								py: 2,
								m: 0,
								width: {
									phone: "100%",
									tablet: "40%",
									laptop: "30%",
								},
								background: "none",
							}}
						>
							<Typography
								component="p"
								sx={{
									color: "grey.500",
									textAlign: "right",
								}}
							>
								2022 Loopstudios. All rights
								reserved.
							</Typography>
						</Paper>
					</Grid>
				</Box>
			</Box>
		</>
	);
}
