// __NEXT JS COMPONENTS__
import Head from "next/head";
import Image from "next/image";

// __MUI COMPONENTS__
import {
	Box,
	Typography,
	Grid,
	Paper,
} from "@mui/material";
import { grey } from "@mui/material/colors";

// __CUSTOM COMPONENTS__
import HomeImageProfile from "../components/HomeImageProfile";

// __SVG ICONS
import facebook from "../public/svg/icon-facebook.svg";
import twitter from "../public/svg/icon-twitter.svg";
import pinterest from "../public/svg/icon-pinterest.svg";
import instagram from "../public/svg/icon-instagram.svg";

export default function Home() {
	return (
		<>
			<Head>
				<title>Loop Studios</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Box className="HOME_PAGE_CONTAINER" sx={{
        mx: {phone: "auto"},
        maxWidth: {phone: "350px"},
        width: {phone: "300px"}
      }}>
				<Box
					component="header"
					sx={{
						py: { phone: 5, laptop: 8 },
						mb: { phone: 5 },
						height: {
							tabletxl: "40vh",
							laptop: "50vh",
							desktop: "70vh",
						},
            position: "relative",
            "&::before": {
              content: "''",
              position: "absolute",
              top: 0,
              left: 0,
              width: "100%",
              height: "100%",
              zIndex: -1
            }
					}}
				>
					<Box
						component="nav"
						sx={{
							display: "flex",
							alignItems: "center",
							position: "relative",
							maxWidth: {
								desktopxl: "1100px",
							},
							zIndex: 10,
						}}
					>
						<Typography
							variant="subtitle1"
							className="logo"
							sx={{
								flex: 1,
							}}
						>
							INSURE
						</Typography>

						<Box
							className="NAV_LINKS"
							sx={{
								display: {
									phone: "none",
									tabletxl: "flex",
								},
								alignItems: {
									tabletxl: "baseline",
								},
							}}
						>
							<Box
								className="links"
								sx={{ mr: { tabletxl: 5 } }}
							>
								<Typography
									variant="subtitle2"
									sx={{
										mx: {
											tabletxl: 0.8,
											laptop: 2,
										},
									}}
								>
									HOW WE WORK
								</Typography>

								<Typography
									variant="subtitle2"
									sx={{
										mx: {
											tabletxl: 0.8,
											laptop: 2,
										},
									}}
								>
									BLOG
								</Typography>

								<Typography
									variant="subtitle2"
									sx={{
										mx: {
											tabletxl: 0.8,
											laptop: 2,
										},
									}}
								>
									ACCOUNT
								</Typography>

								<Typography
									variant="subtitle2"
									sx={{
										mx: {
											tabletxl: 0.8,
											laptop: 2,
										},
									}}
								>
									Blog
								</Typography>
							</Box>

							<Box
								component="button"
								sx={{
									py: 1,
									px: 2,
									display: "block",
									border: "none",
									outline: "none",
									backgroundColor:
										"white",
									border: "2px solid hsl(256, 26%, 20%)",
									transform: {
										tabletxl:
											"scale(.7)",
										tabletxl:
											"scale(.8)",
									},
								}}
							>
								VIEW PLANS
							</Box>
						</Box>

						<Box
							sx={{
								display: {
									phone: "flex",
									tabletxl: "none",
								},
								flexDirection: "column",
								justifyContent:
									"space-between",
								width: "25px",
								height: "15px",
							}}
						>
							<Box
								component="span"
								className="line"
								sx={{
									width: "100%",
									height: {
										phone: "1px",
									},
									backgroundColor:
										"black",
								}}
							></Box>
							<Box
								component="span"
								className="line"
								sx={{
									width: "100%",
									height: {
										phone: ".8px",
									},
									backgroundColor:
										"black",
								}}
							></Box>
							<Box
								component="span"
								className="line"
								sx={{
									width: "100%",
									height: {
										phone: "1px",
									},
									backgroundColor:
										"black",
								}}
							></Box>
						</Box>
					</Box>

					<Box
						component="section"
						className="HEADER_BODY"
						sx={{
							my: { phone: 5, tabletxl: 10 },
						}}
					>
						<Paper
							elevation={0}
							sx={{
								p: 3,
								px: { laptop: 6 },
								borderRadius: "0px",
								border: "3px solid white",
								background: "none",
								width: { tablet: "65%" },
								maxWidth: {
									tabletxl: "420px",
								},
							}}
						>
							<Typography
								variant="h1"
								sx={{ color: "white" }}
							>
								IMMERSIVE EXPERIENCES THAT
								DELIVER
							</Typography>
						</Paper>
					</Box>
				</Box>

				<Box
					component="main"
					sx={{
						mx: { laptop: "auto" },
						maxWidth: {
							laptop: "900px",
							desktop: "1000px",
							desktopxl: "1200px",
						},
					}}
				>
					<Grid
						container
						component="section"
						sx={{
							my: 10,
							position: "relative",
						}}
					>
						<Grid
							item
							phone={12}
							tabletxl={7}
							sx={{
								height: {
									phone: "25vh",
									tabletxl: "40vh",
									laptop: "50vh",
									desktop: "60vh",
								},
							}}
						>
							<Box
								sx={{
									m: 0,
									p: 0,
									width: "100%",
									height: "100%",
									position: "relative",
								}}
							>
								<Image
									src="/images/desktop/image-interactive.jpg"
									alt="Picture of am man wearing a vr head set"
									layout="fill"
									objectFit="contain"
									className="interactive-image"
								/>
							</Box>
						</Grid>

						{/* <Grid
							item
							phone={0}
							tabletxl={5}
							sx={{
								height: {
									tabletxl: "50vh",
									laptop: "65vh",
								},
							}}
						></Grid> */}

						<Grid
							item
							phone={12}
							tabletxl={7}
							sx={{
								position: {
									phone: "relative",
									tabletxl: "absolute",
								},
								bottom: 0,
								right: {
									phone: 0,
									laptop: 150,
								},
							}}
						>
							<Paper
								elevation={0}
								sx={{
									p: 5,

									width: {
										tabletxl: "100%",
									},
									maxWidth: {
										tabletxl: "420px",
									},
								}}
							>
								<Typography
									variant="h2"
									sx={{
										mb: 3,
										width: {
											phone: "80%",
										},
									}}
								>
									THE LEADER IN
									INTERACTIVE VR
								</Typography>

								<Typography
									variant="body1"
									sx={{
										color: "grey.400",
									}}
								>
									Founded in 2011,
									Loopstudios has been
									producing world-class
									virtual reality projects
									for some of the best
									companies around the
									globe. Our award-winning
									creations have
									transformed buisnesses
									through digital
									experiences that bind to
									their brand.
								</Typography>
							</Paper>
						</Grid>
					</Grid>

					<Grid
						container
						component="section"
						sx={{ my: 10 }}
					>
						<Paper
							elevation={0}
							sx={{
								m: 0,
								mb: 2,
								p: 0,
								display: "flex",
								justifyContent:
									"space-between",
								alignItems: "baseline",
								width: "100%",
							}}
						>
							<Typography variant="h3">
								Our Creation
							</Typography>

							<Box
								component="button"
								sx={{
									m: 0,
									px: 1.2,
									py: 0.8,
									border: "2px solid black",
									backgroundColor:
										"white",
									letterSpacing: "5px",
									fontSize: {
										phone: ".5rem",
										tabletxl: ".65rem",
										laptop: ".75rem",
									},
									cursor: "pointer",
								}}
							>
								SEE ALL
							</Box>
						</Paper>

						<Grid
							container
							className="gallery"
							sx={{ position: "relative" }}
						>
							<HomeImageProfile option={0} />
							<HomeImageProfile option={1} />
							<HomeImageProfile option={2} />
							<HomeImageProfile option={3} />
							<HomeImageProfile option={4} />
							<HomeImageProfile option={5} />
							<HomeImageProfile option={6} />
							<HomeImageProfile option={7} />
						</Grid>
					</Grid>
				</Box>

				<Box
					component="footer"
					sx={{
						m: 0,
						py: { phone: 5 },
						px: { phone: 5, laptop: 10 },
						color: "white",
						backgroundColor: "black",
					}}
				>
					<Grid
						item
						phone={12}
						sx={{
							display: { tablet: "flex" },
							justifyContent: {
								tablet: "space-between",
							},
						}}
					>
						<Paper
							elevation={0}
							className="logo"
							sx={{
								background: "none",
								mb: { phone: 2 },
							}}
						>
							<Typography
								variant="subtitle2"
								component="a"
								sx={{
									color: "white",
									fontWeight: "600",
								}}
							>
								loopstudios
							</Typography>
						</Paper>

						<Paper
							elevation={0}
							className="socialmedia-links"
							sx={{ background: "none" }}
						>
							<Box
								component="a"
								sx={{
									mr: 2,
									display: "inline-block",
									width: "1rem",
									height: "1rem",
								}}
							>
								<Image
									src={facebook}
									alt=""
								/>
							</Box>

							<Box
								component="a"
								sx={{
									mr: 2,
									display: "inline-block",
									width: "1rem",
									height: "1rem",
								}}
							>
								<Image
									src={twitter}
									alt=""
								/>
							</Box>

							<Box
								component="a"
								sx={{
									mr: 2,
									display: "inline-block",
									width: "1rem",
									height: "1rem",
								}}
							>
								<Image
									src={pinterest}
									alt=""
								/>
							</Box>

							<Box
								component="a"
								sx={{
									mr: 2,
									display: "inline-block",
									width: "1rem",
									height: "1rem",
								}}
							>
								<Image
									src={instagram}
									alt=""
								/>
							</Box>
						</Paper>
					</Grid>

					<Grid
						item
						phone={12}
						sx={{
							display: { tablet: "flex" },
							justifyContent: {
								tablet: "space-between",
							},
						}}
					>
						<Paper
							elevation={0}
							className="footer-links"
							sx={{
								py: 2,
								m: 0,
								width: {
									phone: "100%",
									tablet: "50%",
									laptop: "30%",
									desktop: "20%",
								},
								display: "flex",
								justifyContent:
									"space-between",
								background: "none",
							}}
						>
							<Typography
								component="a"
								sx={{
									mr: 2,
									color: "grey.400",
									cursor: "pointer",
								}}
							>
								About
							</Typography>
							<Typography
								component="a"
								sx={{
									mr: 2,
									color: "grey.400",
									cursor: "pointer",
								}}
							>
								Careers
							</Typography>
							<Typography
								component="a"
								sx={{
									mr: 2,
									color: "grey.400",
									cursor: "pointer",
								}}
							>
								Events
							</Typography>
							<Typography
								component="a"
								sx={{
									mr: 2,
									color: "grey.400",
									cursor: "pointer",
								}}
							>
								Products
							</Typography>
							<Typography
								component="a"
								sx={{
									color: "grey.400",
									cursor: "pointer",
								}}
							>
								Support
							</Typography>
						</Paper>

						<Paper
							elevation={0}
							phone={12}
							sx={{
								py: 2,
								m: 0,
								width: {
									phone: "100%",
									tablet: "40%",
									laptop: "30%",
								},
								background: "none",
							}}
						>
							<Typography
								component="p"
								sx={{
									color: "grey.500",
									textAlign: "right",
								}}
							>
								2022 Loopstudios. All rights
								reserved.
							</Typography>
						</Paper>
					</Grid>
				</Box>
			</Box>
		</>
	);
}
